/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demokrautur;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Phil
 */
public class MainFrame extends javax.swing.JFrame {

    private static int hohe = 20;
    private static int lange = 20;
    private static int reload = 1000;

    private static ArrayList<Boolean> spielfeld;
    private static Random random = new Random();

    private void ausgabeTest() {
        spielPanel.removeAll();

        for (int i = 0; i < lange * hohe; i++) {
            JPanel bewohner = new JPanel();

            if (spielfeld.get(i)) {
                bewohner.setBackground(Color.BLACK);
            } else {
                bewohner.setBackground(Color.RED);
            }
            spielPanel.add(bewohner);
            bewohner.setVisible(true);
        }

        spielPanel.revalidate();
        spielPanel.repaint();
    }

    private void gameloop() {

        Wraparound wraparound = new Wraparound(hohe, lange);
        int zahl = 0;

        for (int i = 0; i < 100000; i++) {
            int bewohner = random.nextInt((hohe * lange)) + 1;
            wraparound.setBewohner(bewohner);
            int randomNachbar = (random.nextInt(4) + 1);
            switch (randomNachbar) {
                case 1:
                    randomNachbar = wraparound.getUp();
                    break;
                case 2:
                    randomNachbar = wraparound.getRight();
                    break;
                case 3:
                    randomNachbar = wraparound.getDown();
                    break;
                case 4:
                    randomNachbar = wraparound.getLeft();
                    break;
                default:
                    break;
            }

            if (spielfeld.get(bewohner - 1) != spielfeld.get(randomNachbar - 1)) {
                spielfeld.set(randomNachbar - 1, random.nextBoolean());
            }
            zahl++;
            if (zahl == reload) {
                System.out.println("-----------------");
                ausgabeTest();
                zahl = 0;
            }

        }

    }

    /**
     * Creates new form MainFrame
     *
     *
     * Notizen: True = Schwartz = KPCh False = Rot = RKdK
     */
    public MainFrame() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interation_int = new javax.swing.JSpinner();
        start_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        spielPanel = new javax.swing.JPanel();
        interration_txt = new javax.swing.JLabel();
        rkdk_txt = new javax.swing.JLabel();
        kpch_txt = new javax.swing.JLabel();
        rkdk_procent = new java.awt.TextField();
        kpch_procent = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        start_Button.setText("Start");
        start_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_ButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        spielPanel.setLayout(new java.awt.GridLayout(hohe, lange));
        jScrollPane1.setViewportView(spielPanel);

        interration_txt.setText("Interration");

        rkdk_txt.setForeground(new java.awt.Color(255, 0, 0));
        rkdk_txt.setText("RKdK");

        kpch_txt.setBackground(new java.awt.Color(255, 255, 255));
        kpch_txt.setText("KPCh");

        rkdk_procent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rkdk_procent.setEditable(false);
        rkdk_procent.setText("0%");
        rkdk_procent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkdk_procentActionPerformed(evt);
            }
        });

        kpch_procent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kpch_procent.setEditable(false);
        kpch_procent.setText("0%");
        kpch_procent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpch_procentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(kpch_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rkdk_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rkdk_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kpch_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interation_int, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(start_Button)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(interration_txt)
                        .addGap(55, 55, 55)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(interration_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_Button)
                    .addComponent(interation_int, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kpch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kpch_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkdk_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rkdk_procent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_ButtonActionPerformed
        gameloop();
    }//GEN-LAST:event_start_ButtonActionPerformed

    // Ignorieren 

    private void kpch_procentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpch_procentActionPerformed

    }//GEN-LAST:event_kpch_procentActionPerformed

    private void rkdk_procentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkdk_procentActionPerformed

    }//GEN-LAST:event_rkdk_procentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Erstellung Des Spielfeld
        spielfeld = new ArrayList<>();
        randomSpielbrett();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner interation_int;
    private javax.swing.JLabel interration_txt;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField kpch_procent;
    private javax.swing.JLabel kpch_txt;
    private java.awt.TextField rkdk_procent;
    private javax.swing.JLabel rkdk_txt;
    private javax.swing.JPanel spielPanel;
    private javax.swing.JButton start_Button;
    // End of variables declaration//GEN-END:variables

    private static void randomSpielbrett() {

        for (int i = 1; i <= lange * hohe; i++) {
            spielfeld.add(random.nextBoolean());
        }

    }

}
